### ISSUE TITLE
Compilation error with MSVC: Attempting to reference a deleted function

### ISSUE THREAD

**Issue by BullyWiiPlaza** [jhasse/ThreadPool#1]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2280	'std::packaged_task<return_type (void)>::packaged_task(const std::packaged_task<return_type (void)> &)': attempting to reference a deleted function	D:\Cpp\MyProject	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.21.27702\include\functional	979	
```

![image](https://user-images.githubusercontent.com/7620135/60923115-12a06e80-a253-11e9-8ddf-b5eb826d5b4c.png)

Potentially guilty piece of code:
```
std::packaged_task<return_type()> task(
        std::bind(std::forward<F>(f), std::forward<Args>(args)...)
);
```

**Comment by jhasse** [comment]
Does this happen with VS 2017, too?

**Comment by BullyWiiPlaza** [comment]
I'm not sure. It should work with the latest version regardless, so installing `VS 2017` might not do any good. Especially since it takes a long time to install and a couple GBs of unnecessary hard drive space. Maybe you can install `VS 2019` if you haven't yet and try to figure out the issue? I don't really know why the code won't compile. Maybe there's another way to accomplish the same thing but with a syntax accepted by the `MSVC` compiler.

**Comment by antoncxx** [comment]
Had the same problem because forgot to change
 std::queue<std::future<void()>> tasks;
to
std::queue<std::packaged_task<void()>> tasks;

**Comment by vladfaust** [comment]
This is a known MSVC [bug](https://developercommunity.visualstudio.com/content/problem/108672/unable-to-move-stdpackaged-task-into-any-stl-conta.html). Basically, moving a `std::function` (therefore moving `std::packaged_task`) is impossible in MSVC.

**Comment by WanpengQian** [comment]
> This is a known MSVC [bug](https://developercommunity.visualstudio.com/content/problem/108672/unable-to-move-stdpackaged-task-into-any-stl-conta.html). Basically, moving a `std::function` (therefore moving `std::packaged_task`) is impossible in MSVC.

I am so sad MS still not publishing the fix.
[https://developercommunity.visualstudio.com/t/unable-to-move-stdpackaged-task-into-any-stl-conta/108672](https://developercommunity.visualstudio.com/t/unable-to-move-stdpackaged-task-into-any-stl-conta/108672)

Any workaround?

**Comment by vladfaust** [comment]
@WanpengQian yeah, there is a working implementation (_on my machine_). I license it with MIT to anyone wandering:

https://github.com/fancysofthq/fnxc/blob/development/include/fnx/utils/thread_pool.hpp
https://github.com/fancysofthq/fnxc/blob/development/src/cpp/utils/thread_pool.cpp
https://github.com/fancysofthq/fnxc/blob/development/test/cpp/utils/thread_pool.cpp

Ping me if it's 404, I may occasionally remove it 🤷

**Comment by jiezenghuang** [comment]
maybe is  not a bug
```
try to std::move(std::packaged_task)
if (std::packaged_task<return_type()> != std::packaged_task<void()>)
    try to call packaged_task( const packaged_task& ) = delete;  //  C2280: attempting to reference a deleted function
else
    ok;
```

**Comment by BullyWiiPlaza** [comment]
It seems to work now with the latest version of Visual Studio 2022, so we're good 😄
