### ISSUE TITLE
Curious that why to move the destroctor info a split .cpp file

### ISSUE THREAD

**Issue by yqs112358** [jhasse/ThreadPool#3]
Header-only library maybe more convinent for import into the project?

**Comment by jhasse** [comment]
I'm not sure anymore. I think a separate header-only version would be a good idea, maybe in a folder `header-only/`. But I would even prefer to move more stuff in to the .cpp file.

**Comment by yqs112358** [comment]
ok i tried to move destroctor into hpp, and it works just ok
thanks any more
